#!/bin/bash
#SBATCH -J mm_ring
#SBATCH -o runs/mm_par_%j.out
#SBATCH -e runs/mm_par_%j.err
#SBATCH --mail-user filippo.mazzarotto@studenti.unipd.it
#SBATCH --mail-type ALL
#SBATCH -n 1
#SBATCH -p allgroups
#SBATCH -t 00:00:30
#SBATCH --mem 1G
cd $SLURM_SUBMIT_DIR
mpirun -np $SLURM_NTASKS ./mm_par_ring.out